### ISSUE TITLE
안녕하세요. 저도 했던 과정중 참고할만한거 작성해놓겠습니다

### ISSUE THREAD

**Issue by NamWoo** [ruddyscent/adlab-e2e#1]
안녕하세요!
같은 모두연 옆반(판단제어) 소속 김남우 입니다.

이렇게 잘 작성해주신것도 모르고 혼자 헤매고 결국 해결은 했지만.. 미리 못찾아봐 너무 아쉽네요.. (제 주말.. 연휴가..)
너무 잘 작성해주신거 참고가 되었기에, 저도 잘 공유드리도록 할게요!

* **_아래 내용은 추후 정리해서 md로 만들어 공유하도록 하겠습니다._**

```bash
# carla latest가 현재 0.9.15로 되어있어서, latest로 최초에 pull했더니 안됐네요. 
# 0.9.15 따로 지정해야 이상없이 client와 붙었습니다.

sudo docker pull carlasim/carla:0.9.15
sudo docker run --privileged --gpus all --net=host -e DISPLAY=$DISPLAY carlasim/carla:0.9.15 /bin/bash ./CarlaUE4.sh
```

![Screenshot from 2024-06-09 21-46-26](https://github.com/ruddyscent/adlab-e2e/assets/8021479/6f52d6ab-7941-4748-89da-04b82e55314a)

위 이미지는 버전 안맞을때 화면입니다. 0.9.15로 따로 지정하면 문제없이 풀렸습니다.

```bash
# 만들어주신거 참고해서 다시 진행했습니다.

git clone -b first-step https://github.com/ruddyscent/adlab-e2e
cd adlab-e2e
sudo docker build --tag pytorch-carla:0.1 -f Dockerfile-jupyter .
sudo docker run --privileged --gpus all --net=host -e DISPLAY=$DISPLAY -it --rm  pytorch-carla:0.1 jupyter notebook
```

아래 처럼 오류가 나타났을때, 돌고 돌아 docker rootless 로 싹 갈아엎고 해봤는데요.
```bash
Refusing to run with the root privileges.
```
docker rootless는 GPU사용에 제한이 있다고 하네요 

```bash
nw@hpc06:~$ docker run --privileged --gpus all --net=host -e DISPLAY=$DISPLAY carlasim/carla:0.9.15 /bin/bash ./CarlaUE4.sh
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: open /sys/fs/cgroup/devices/user.slice/devices.allow: permission denied: unknown.
```

결국 현재는 이상없이 잘 됩니다! 

![image](https://github.com/ruddyscent/adlab-e2e/assets/8021479/d3791a78-c433-4f1f-9e97-9e8ddddb85f9)

**Comment by NamWoo** [comment]
이제 다음은 ros 붙이는 거네요 !

**Comment by ruddyscent** [comment]
저도 ros + autoware까지 가는 것을 목표로 진행하고 있습니다. 여기까지 가면 논문에 나온 모델들을 손쉽게 적용해 볼 수 있을 것 같아요.

아울러 다른 랩 원들도 모델 테스트 및 훈련 환경을 갖출 수 있도록 따라 해보기 세션을 진행하면 좋을 것 같아요. 같이 하셨으면 좋겠어요.
