### ISSUE TITLE
따라서 진행하던 중, 오류 발생한것들 공유드립니다.

### ISSUE THREAD

**Issue by NamWoo** [ruddyscent/adlab-e2e#5]
![image](https://github.com/user-attachments/assets/3b7d6435-c17e-4570-bab6-c4d3ec6994b1)

폴더내에 ignore로 빠져있는 파일이니 이건 스크립트 실행에 앞서서 다운 받으면 될거 같습니다.

제가 사용한 스크립트 아래 추가했습니다

```
wget -O AdditionalMaps_0.9.15.tar https://tiny.carla.org/additional-maps-0-9-15-linux
```

**Comment by ruddyscent** [comment]
추가맵은 내려받는 데 시간이 걸려서 Dockerfile에 넣지 않았습니다. 별도로 내려받은 후에 저장소의 루트에 저장한 후에 진행해 주세요.
