### ISSUE TITLE
failed to solve: process "/bin/sh -c apt-get install -y ros-humble-pcl-conversions" did not complete successfully

### ISSUE THREAD

**Issue by NamWoo** [ruddyscent/adlab-e2e#6]
```bash
116.5 Ign:198 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
118.7 Ign:131 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5quickparticles5 amd64 5.15.3+dfsg-1
120.3 Ign:198 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
124.3 Err:131 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5quickparticles5 amd64 5.15.3+dfsg-1
124.3   Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
125.9 Ign:198 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
186.4 Err:198 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
186.4   Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
186.4 Fetched 465 MB in 3min 4s (2521 kB/s)
186.4 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/libqt5quickparticles5_5.15.3%2bdfsg-1_amd64.deb  Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
186.4 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jdk-headless_11.0.24%2b8-1ubuntu3%7e22.04_amd64.deb  Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
186.4 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve: process "/bin/sh -c apt-get install -y ros-humble-pcl-conversions" did not complete successfully: exit code: 100
```

이 오류가 발생했습니다.

`ros.Dockerfile`

에서 

`RUN apt-get install -y ros-humble-pcl-conversions`

이거 따로 추가해서 진행했는데도 같은 오류내요.

**Comment by NamWoo** [comment]
실행은

`docker-compose build --no-cache`

이렇게 했고 readme에 써주신대로

`my.env`를 만들고
```env
# .env file
CARLA_GPU_DEVICES=0 # GPU devices assigned to the Carla container
CARLA_RPC_PORT=2000 # Port number for Carla clients to connect (default: 2000)

JUPYTER_GPU_DEVICES=0 # GPU device assigned to the Jupyter container
JUPYTER_PORT=8888     # Port number for the Jupyter server (default: 8888)
JUPYTER_TOKEN=letmein # Authentication token for the Jupyter server
```

추가해서 진행했습니다.

**Comment by ruddyscent** [comment]
> 실행은
> 
> `docker-compose build --no-cache`
> 
> 이렇게 했고 readme에 써주신대로
> 
> `my.env`를 만들고
> 
> ```dotenv
> # .env file
> CARLA_GPU_DEVICES=0 # GPU devices assigned to the Carla container
> CARLA_RPC_PORT=2000 # Port number for Carla clients to connect (default: 2000)
> 
> JUPYTER_GPU_DEVICES=0 # GPU device assigned to the Jupyter container
> JUPYTER_PORT=8888     # Port number for the Jupyter server (default: 8888)
> JUPYTER_TOKEN=letmein # Authentication token for the Jupyter server
> ```
> 
> 추가해서 진행했습니다.

`.env` 파일을 `my.env`로 변경하면 Docker는 기본적으로 이를 인식하지 않습니다. `docker-compose`나 `docker run` 명령어에서 `--env-file` 옵션을 사용하여 `my.env` 파일을 명시적으로 지정해야 합니다.

**Comment by ruddyscent** [comment]
> ```shell
> 116.5 Ign:198 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
> 118.7 Ign:131 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5quickparticles5 amd64 5.15.3+dfsg-1
> 120.3 Ign:198 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
> 124.3 Err:131 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5quickparticles5 amd64 5.15.3+dfsg-1
> 124.3   Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
> 125.9 Ign:198 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
> 186.4 Err:198 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.24+8-1ubuntu3~22.04
> 186.4   Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
> 186.4 Fetched 465 MB in 3min 4s (2521 kB/s)
> 186.4 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/q/qtdeclarative-opensource-src/libqt5quickparticles5_5.15.3%2bdfsg-1_amd64.deb  Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
> 186.4 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jdk-headless_11.0.24%2b8-1ubuntu3%7e22.04_amd64.deb  Error reading from server. Remote end closed connection [IP: 185.125.190.83 80]
> 186.4 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ------
> failed to solve: process "/bin/sh -c apt-get install -y ros-humble-pcl-conversions" did not complete successfully: exit code: 100
> ```
> 
> 이 오류가 발생했습니다.
> 
> `ros.Dockerfile`
> 
> 에서
> 
> `RUN apt-get install -y ros-humble-pcl-conversions`
> 
> 이거 따로 추가해서 진행했는데도 같은 오류내요.

일단, leaderboard와 scenario runner가 foxy를 지원해서 `rox.Dockerfile`의 첫 부분에 있는 ROS 버전 설정 부분을 다음과 같이 변경하셔야 합니다. 
```
ARG ROS_VER=foxy
```

현재 ROS 설정 부분에 문제가 있는 것 같아요. 혹시 ROS 컨테이너를 사용하지 않으신다면, `compose.yml`에서 `ros` 컨테이너 관련 부분을 삭제하시고 진행하셔도 좋을 것 같습니다.

**Comment by ruddyscent** [comment]
확인해 보니 문제없이 빌드 및 실행이 됩니다. `ROS_VER=humble`은 그대로 유지해 주세요.

아마도 패키지 저장소에 잠시 문제가 있었던 것 같아요.
